FinalProject-2nd edition/Models/BookViewModel.cs
using FinalProject_2nd_edition.DataModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FinalProject_2nd_edition.Models
{
    public class BookViewModel
    {
        public int BookId { get; set; }

        [StringLength(30, MinimumLength = 2)]
        [Required]
        public string Name { get; set; }
        public string PictureUrl { get; set; }

        
        public string Description { get; set; }

        public int GenreId { get; set; }
        public Genre Genre { get; set; }
        public int AuthorId { get; set; }
        public Author Author { get; set; }
        public ICollection<SelectListItem> AuthorList { get; set; }
        public ICollection<SelectListItem> GenreList { get; set; }
    }
}

FinalProject-2nd edition/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalProject_2nd_edition.Data;
using FinalProject_2nd_edition.DataModels;
using FinalProject_2nd_edition.Services;
using FinalProject_2nd_edition.Models;
using Microsoft.AspNetCore.Authorization;

namespace FinalProject_2nd_edition.Controllers
{
    [Authorize(Policy = "RequireAdministratorRole")]
    public class BooksController : Controller
    {
        private readonly IBookService bookService;

        public BooksController(IBookService bookService)
        {
            this.bookService = bookService;
        }

        // GET: Books
        [AllowAnonymous]
        public IActionResult Index( string searchString, int currentPage = 1)
        {
            var skip = (currentPage - 1) * 4;
            var take = 4;
            var books = this.bookService.GetAll(searchString, skip, take);
            var totalBooks = this.bookService.GetCount();

            var totalPages = totalBooks / 4;
            if (totalBooks % 4 > 0)
            {
                totalPages++;
            }

            var model = new BookViewModel_List()
            {
                List = GetListofBooksViewModel(books),
                CurrentPage = currentPage,
                TotalPages = totalPages
            };
            return View(model);
        }

        // GET: Books/Details/5
        [AllowAnonymous]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = this.bookService.GetById(id);
            var model = GetBookViewModel(book);
            if (book == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // GET: Books/Create
       
        public IActionResult Create()
        {
            var book = new Book();
            book.AuthorList = (ICollection<SelectListItem>)this.bookService.CreateAuthorDropDownList();
            book.GenreList = (ICollection<SelectListItem>)this.bookService.CreateGenreDropDownList();
            var model = GetBookViewModel(book);
            return View(model);
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("BookId,Name,PictureUrl,Description,GenreId,AuthorId")] BookViewModel book)
        {
            if (ModelState.IsValid)
            {
                var bookToAdd = GetBookDataModel(book);
                if (BookExists(bookToAdd.Name))
                {
                    ModelState.AddModelError("name", "The book already exists");
                }
               
                else
                {
                    this.bookService.Add(bookToAdd);
                    this.bookService.AddBookInAuthor(bookToAdd);
                    this.bookService.AddBookInGenre(bookToAdd);
                    this.bookService.AddInAuthorGenre(bookToAdd);

                    return RedirectToAction(nameof(Index));
                }
            }
            
            return View(book);
        }
        public ActionResult AddAuthor(string authorName, string authorDescription, string pictureUrl)
        {
            var author = new Author();
            author.Name = authorName;
            author.Details = authorDescription;
            author.PictureUrl = pictureUrl;
            this.bookService.AddAuthor(author);
            var id = author.AuthorId;
            return Ok(new
            {
                Id = id,
                Name = authorName,
               
            }) ;
        }

        public IActionResult AddGenre(string genreName)
        {
            var genre = new Genre();
            genre.Name = genreName;
            this.bookService.AddGenre(genre);
            var id = genre.GenreId;
            return Ok(new
            {
                Id = id,
                Name = genreName,
            });
        }

        // GET: Books/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = this.bookService.GetById(id);
            book.AuthorList = (ICollection<SelectListItem>)this.bookService.CreateAuthorDropDownList();
            book.GenreList = (ICollection<SelectListItem>)this.bookService.CreateGenreDropDownList();
            var model = GetBookViewModel(book);

            if (book == null)
            {
                return NotFound();
            }
           
            return View(model);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("BookId,Name,PictureUrl, Description,GenreId,AuthorId")] BookViewModel book)
        {
            if (id != book.BookId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    this.bookService.Update(GetBookDataModel(book));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.BookId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
           
            return View(book);
        }

        // GET: Books/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = this.bookService.GetById(id);
            var model = GetBookViewModel(book);
            if (book == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var book = this.bookService.GetById(id);
            this.bookService.Delete(book);
            this.bookService.DeleteBookInAuthor(book);
            this.bookService.DeleteBookInGenre(book);
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return this.bookService.BookExists(id);
        }

        private bool BookExists(string bookName)
        {
            return this.bookService.BookExists(bookName);
        }

        private Book GetBookDataModel (BookViewModel book)
        {
            return new Book
            {
                BookId = book.BookId,
                Name = book.Name,
                PictureUrl = book.PictureUrl,
                Description = book.Description,
                AuthorId = book.AuthorId,
                Author = book.Author,
                GenreId = book.GenreId,
                Genre = book.Genre,
                AuthorList = book.AuthorList,
                GenreList = book.GenreList

            };
        }
        
        private BookViewModel GetBookViewModel(Book book)
        {
            var model = new BookViewModel()
            {
                BookId = book.BookId,
                Name = book.Name,
                PictureUrl = book.PictureUrl,
                Description = book.Description,
                AuthorId = book.AuthorId,
                Author = book.Author,
                GenreId = book.GenreId,
                Genre = book.Genre,
                AuthorList = book.AuthorList,
                GenreList = book.GenreList

            };
            return model;
        }

        private ICollection<BookViewModel> GetListofBooksViewModel(List<Book> sourse)
        {
            var books = new List<BookViewModel>();
            foreach (var g in sourse)
            {
                books.Add(GetBookViewModel(g));
            }
            return books;
        }
    }
}

FinalProject-2nd edition/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalProject_2nd_edition.Data;
using FinalProject_2nd_edition.DataModels;
using FinalProject_2nd_edition.Services;
using FinalProject_2nd_edition.Models;
using Microsoft.AspNetCore.Authorization;

namespace FinalProject_2nd_edition.Controllers
{
    [Authorize(Policy = "RequireAdministratorRole")]
    public class GenresController : Controller
    {
        private readonly IGenreService genreService;

        public GenresController(IGenreService genreService)
        {
            this.genreService = genreService;
        }

        // GET: Genres
        [AllowAnonymous]
        public IActionResult Index(string searchString, int currentPage = 1)
        {
            var skip = (currentPage - 1) * 3;
            var take = 3;
            var genres = this.genreService.GetAll(searchString, skip, take);
            var totalGenres = this.genreService.GetCount();

            var totalPages = totalGenres / 3;
            if (totalGenres % 3 > 0)
            {
                totalPages++;
            }

            var model = new GenreViewModel_List()
            {
                List = GetListofGenresViewModel(genres),
                CurrentPage = currentPage,
                TotalPages = totalPages
            };
            return View(model);
        }

        // GET: Genres/Details/5
        [AllowAnonymous]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = this.genreService.GetById(id);
            var model = GetGenreViewModel(genre);

            if (genre == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // GET: Genres/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("GenreId,Name")] GenreViewModel genre)
        {
            if (ModelState.IsValid)
            {
                if (GenreExists(GetGenreDataModel(genre).Name))
                {
                    ModelState.AddModelError("name", "The genre already exists");
                }
                else
                {
                    this.genreService.Add(GetGenreDataModel(genre));

                    return RedirectToAction(nameof(Index));
                }
            }
            return View(genre);
        }

        // GET: Genres/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = this.genreService.GetById(id);
            var model = GetGenreViewModel(genre);
            if (genre == null)
            {
                return NotFound();
            }
            return View(model);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("GenreId,Name")] GenreViewModel genre)
        {
            if (id != genre.GenreId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    this.genreService.Update(GetGenreDataModel(genre));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genre.GenreId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = this.genreService.GetById(id);
            var model = GetGenreViewModel(genre);
            if (genre == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            
                var genre = this.genreService.GetById(id);
                var model = GetGenreViewModel(genre);
            if (ModelState.IsValid)
            {
                if (genre.Books.Count != 0)
                {
                    ModelState.AddModelError("name", "You could not delete genre if there are books of this genre");
                    
                }
                
                else
                {
                    this.genreService.Delete(genre);
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }
       

        private bool GenreExists(int id)
        {
            return this.genreService.GenreExists(id);

        }

        private bool GenreExists(string name)
        {
            return this.genreService.GenreExists(name);

        }

        private Genre GetGenreDataModel(GenreViewModel genre)
        {
            return new Genre
            {
                GenreId = genre.GenreId,
                Name = genre.Name
            };
        }

        private GenreViewModel GetGenreViewModel(Genre g)
        {
            var model = new GenreViewModel();
            model.GenreId = g.GenreId;
            model.Name = g.Name;
            if (g.Books != null)
            {
                var authors = new List<Author>();
                foreach (var item in g.AuthorGenres)
                {
                    authors.Add(item.Author);
                }

                model.Books = g.Books.ToList();
                model.Authors = authors;
            }
            else
            {
                model.Books = null;
                model.Authors = null;
            }
            return model;
        }
        
        private IEnumerable<GenreViewModel> GetListofGenresViewModel(List<Genre> sourse)
        {
            var genres = new List<GenreViewModel>();
            foreach (var g in sourse)
            {
                genres.Add(GetGenreViewModel(g));
            }
            return genres;
        }

    }


}

FinalProject-2nd edition/Views/Books/Create.cshtml
@model FinalProject_2nd_edition.Models.BookViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
               <div class="form-group">
                <label asp-for="PictureUrl" class="control-label"></label>
                <input asp-for="PictureUrl" class="form-control" />
                <span asp-validation-for="PictureUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <select asp-for="AuthorId" id="sel-auth" class="form-control" asp-items="@Model.AuthorList">
                    <option>Please select author</option>
                </select>
                <span asp-validation-for="Author.Name" class="text-danger"></span>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add-modal">Add author</button>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <select asp-for="GenreId" id="sel-gen" class="form-control" asp-items="@Model.GenreList">
                    <option>Please select genre</option>
                </select>

                <span asp-validation-for="Genre.Name" class="text-danger"></span>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add-modal2">Add genre</button>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<div class="modal fade" id="add-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Add author</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <label>Author name</label>
                <input id="author" class="form-control" type="text" />
                <label>PictureUrl</label>
                <input id="pictureUrl" class="form-control" type="text" />
                <label>Details</label>
                <input id="description" class="form-control" type="text" />
            </div>
            <div class="modal-footer">
                <button type="button" id="cls-btn" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button onclick="addAuthor()" class="btn btn-danger">Add author</button>
            </div>

        </div>
    </div>
</div>


<script>
    
    const addAuthor = () => {
        let authortoAdd = document.getElementById("author").value;
        let descriptiontoAdd = document.getElementById("description").value;
        let pictureUrltoAdd = document.getElementById("pictureUrl").value;
        fetch(`/Books/AddAuthor?authorName=${authortoAdd}&authorDescription=${descriptiontoAdd}&pictureUrl=${descriptiontoAdd}`)
            .then((response) => response.json())
            .then((data) => handleResponse(data));
     }

    const handleResponse = (data) => {
        let selectElement = document.getElementById("sel-auth");
        let opt = document.createElement('option');
        opt.value = data.id;
        opt.innerHTML = data.name;
        selectElement.appendChild(opt);
        document.getElementById("cls-btn").click();
    }
</script>

<div class="modal fade" id="add-modal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Add genre</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input id="genre" class="form-control" type="text" />
            </div>
            <div class="modal-footer">
                <button type="button" id="cls-btn1" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button onclick="addGenre()" class="btn btn-danger">Add genre</button>
            </div>
        </div>
    </div>
</div>

<script>
    const addGenre = () => {
        let genretoAdd = document.getElementById("genre").value;
        fetch(`/Books/AddGenre?genreName=${genretoAdd}`)
            .then((response) => response.json())
            .then((data) => handleResponse2(data));
    }

    const handleResponse2 = (data) => {
        let selectElement = document.getElementById("sel-gen");
        let opt = document.createElement('option');
        opt.value = data.id;
        opt.innerHTML = data.name;
        selectElement.appendChild(opt);
        document.getElementById("cls-btn1").click();

    }
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalProject-2nd edition/Views/Books/Delete.cshtml
@model FinalProject_2nd_edition.Models.BookViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre.Name)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BookId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FinalProject-2nd edition/Views/Books/Details.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@model FinalProject_2nd_edition.Models.BookViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>@Html.DisplayFor(model => model.Name)</h1>

<div>
    <h4>
         <a asp-controller="Authors" asp-action="Details" asp-route-id=@Model.Author.AuthorId>@Model.Author.Name</a>
    </h4>
    <hr />
    <dl class="row">
         <dt class="col-sm-2">
            <img src="@Model.PictureUrl" class="img-thumbnail" >
        </dt>
        <dd class="col-sm-10">
           
            @Html.DisplayFor(model => model.Description)
            <br />    
            <br /> 
            <a asp-controller="Genres" asp-action="Details" asp-route-id=@Model.Genre.GenreId>"@Model.Genre.Name"</a>
        </dd>
      
    </dl>
</div>
<div>
    @if ((await AuthorizationService.AuthorizeAsync(User, "RequireAdministratorRole")).Succeeded)
    {
        <a asp-action="Edit" asp-route-id="@Model.BookId">Edit</a>
    }
    <a asp-action="Index">Back to List</a>
</div>

FinalProject-2nd edition/Views/Books/Edit.cshtml
@model FinalProject_2nd_edition.Models.BookViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
             <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BookId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PictureUrl" class="control-label"></label>
                <input asp-for="PictureUrl" class="form-control" />
               
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
              <div class="form-group">
                <label asp-for="Author.Name" class="control-label"></label>
                <select asp-for="AuthorId" class="form-control" asp-items="@Model.AuthorList">
                    <option>Please select author</option>
                </select>
                <span asp-validation-for="Author.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre.Name" class="control-label"></label>
                <select asp-for="GenreId" class="form-control"asp-items="@Model.GenreList">
                    <option>Please select genre</option>
                 </select>
                <span asp-validation-for="Genre.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalProject-2nd edition/Views/Books/Index.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@model FinalProject_2nd_edition.Models.BookViewModel_List


@{
    ViewData["Title"] = "Index";
}

<h1>Books</h1>
@if ((await AuthorizationService.AuthorizeAsync(User, "RequireAdministratorRole")).Succeeded)
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}
@using (Html.BeginForm())
{
    <p>
        Search by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

<div class="row">
    @foreach (var item in Model.List)
    {
        <div class="col-md-3 mb-3 mb-md-0">
            <div class="card" style="background:#d4e0f6">
                <h5 class="card-title text-center" style=text-align: center><a asp-controller="Books" asp-action="Details" asp-route-id="@item.BookId">@Html.DisplayFor(modelItem => item.Name)</a></h5>
                <p class="card-title text-center" style=text-align: center><a asp-controller="Authors" asp-action="Details" asp-route-id="@item.Author.AuthorId">@Html.DisplayFor(modelItem => item.Author.Name)</a></p>
                <img class="card-img-top align-self-center" src="@item.PictureUrl" alt="Card image" style="width:220px;height:300px;">
                <div class="card-body">
                    <p class="card-title text-center"><a asp-controller="Genres" asp-action="Details" asp-route-id="@item.Genre.GenreId">@Html.DisplayFor(modelItem => item.Genre.Name)</a></p>
                    @if ((await AuthorizationService.AuthorizeAsync(User, "RequireAdministratorRole")).Succeeded)
                    {
                        <p class="card-title text-center">
                            
                                <a asp-action="Edit" asp-route-id="@item.BookId">Edit</a>
                                <a asp-action="Delete" asp-route-id="@item.BookId">Delete</a>
                           
                        </p>
                    }
                </div>
            </div>
        </div>
    }
</div>



<nav aria-label="...">
    <ul class="pagination">
        @if (Model.CurrentPage == 1)
        {
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Previous</a>
            </li>
        }
        else
        {
            <li class="page-item">
                <a class="page-link" href="/Books/Index?currentPage=@(Model.CurrentPage-1)" tabindex="-1">Previous</a>
            </li>
        }
        @for (int i = 0; i < Model.TotalPages; i++)
        {
            if (i + 1 == Model.CurrentPage)
            {
                <li class="page-item active">
                    <a class="page-link" href="/Books/Index?currentPage=@(i + 1)">@(i + 1) <span class="sr-only">(current)</span></a>
                </li>
            }
            else
            {
                <li class="page-item"><a class="page-link" href="/Books/Index?currentPage=@(i + 1)">@(i + 1)</a></li>
            }
        }

        @if (Model.CurrentPage == Model.TotalPages)
        {
            <li class="page-item disabled">
                <a class="page-link" href="#">Next</a>
            </li>
        }
        else
        {
            <li class="page-item">
                <a class="page-link" href="/Books/Index?currentPage=@(Model.CurrentPage+1)">Next</a>
            </li>
        }

    </ul>
</nav>