FinalProject-2nd edition/Models/GenreViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using FinalProject_2nd_edition.DataModels;

namespace FinalProject_2nd_edition.Models
{
    public class GenreViewModel
    {
        
        public int GenreId { get; set; }

        [StringLength(30, MinimumLength = 3)]
        [Required]
        public string Name { get; set; }

        public ICollection<Book> Books { get; set; }
        

        public ICollection<Author> Authors { get; set; }
    }
}

FinalProject-2nd edition/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalProject_2nd_edition.Data;
using FinalProject_2nd_edition.DataModels;
using FinalProject_2nd_edition.Services;
using FinalProject_2nd_edition.Models;
using Microsoft.AspNetCore.Authorization;

namespace FinalProject_2nd_edition.Controllers
{
    [Authorize(Policy = "RequireAdministratorRole")]
    public class AuthorsController : Controller
    {
        private readonly IAuthorService authorService;

        public AuthorsController(IAuthorService authorService)
        {
            this.authorService = authorService;
        }

        // GET: Authors
        [AllowAnonymous]
        public IActionResult Index(string searchString, int currentPage = 1)
        {
            var skip = (currentPage - 1) * 3;
            var take = 3;
            var authors = this.authorService.GetAll(searchString, skip, take);
            var totalAuthors = this.authorService.GetCount();

            var totalPages = totalAuthors / 3;
            if (totalAuthors % 3 > 0)
            {
                totalPages++;
            }

            var model = new AuthorViewModel_List()
            {
                List = GetListofAuthorViewModel(authors),
                CurrentPage = currentPage,
                TotalPages = totalPages
            };
            return View(model);
        }

        // GET: Authors/Details/5
        [AllowAnonymous]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = this.authorService.GetById(id);
            var model = GetAuthorViewModel(author);
            if (author == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // GET: Authors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("AuthorId,Name,PictureUrl, Details")] AuthorViewModel author)
        {
            if (ModelState.IsValid)
            {
                if (AuthorExists((GetAuthorDataModel(author).Name)))
                {
                    ModelState.AddModelError("name", "The author already exists");
                }
                else
                {
                    this.authorService.Add(GetAuthorDataModel(author));
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(author);
        }

        private bool AuthorExists(string name)
        {
            return this.authorService.AuthorExists(name);
        }

        // GET: Authors/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = this.authorService.GetById(id);
            var model = GetAuthorViewModel(author);
            if (author == null)
            {
                return NotFound();
            }
            return View(model);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("AuthorId,Name,PictureUrl, Details")] AuthorViewModel author)
        {
            if (id != author.AuthorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    this.authorService.Update(GetAuthorDataModel(author));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorExists(author.AuthorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = this.authorService.GetById(id);
            var model = GetAuthorViewModel(author);
            if (author == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var author = this.authorService.GetById(id);
            var model = GetAuthorViewModel(author);
            if (ModelState.IsValid)
            {
                if (author.Books.Count != 0)
                {
                    ModelState.AddModelError("name", "You could not delete author if there are books  of this author");
                }
                else 
                {
                    this.authorService.Delete(author);
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);

        }

       

        private bool AuthorExists(int id)
        {
            return this.authorService.AuthorExists(id);

        }

        private Author GetAuthorDataModel(AuthorViewModel author)
        {
            return new Author
            {
                AuthorId = author.AuthorId,
                Name = author.Name,
                PictureUrl = author.PictureUrl,
                Details = author.Details
            };
        }

        private AuthorViewModel GetAuthorViewModel(Author a)
        {
            var model = new AuthorViewModel();
            model.AuthorId = a.AuthorId;
            model.Name = a.Name;
            model.PictureUrl = a.PictureUrl;    
            model.Details = a.Details;
            if (a.Books != null)
            {
                var genres = new List<Genre>();
                foreach (var item in a.AuthorGenres)
                {
                    genres.Add(item.Genre);
                }

                model.Books = a.Books.ToList();
                model.Genres = genres;
            }
            else
            {
                model.Books = null;
                model.Genres = null;
            }
            return model;
        }
        
        private IEnumerable<AuthorViewModel> GetListofAuthorViewModel(List<Author> sourse)
        {
            var authors = new List<AuthorViewModel>();
            foreach (var a in sourse)
            {
                authors.Add(GetAuthorViewModel(a));
            }
            return authors;
        }
    }
}

FinalProject-2nd edition/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalProject_2nd_edition.Data;
using FinalProject_2nd_edition.DataModels;
using FinalProject_2nd_edition.Services;
using FinalProject_2nd_edition.Models;
using Microsoft.AspNetCore.Authorization;

namespace FinalProject_2nd_edition.Controllers
{
    [Authorize(Policy = "RequireAdministratorRole")]
    public class BooksController : Controller
    {
        private readonly IBookService bookService;

        public BooksController(IBookService bookService)
        {
            this.bookService = bookService;
        }

        // GET: Books
        [AllowAnonymous]
        public IActionResult Index( string searchString, int currentPage = 1)
        {
            var skip = (currentPage - 1) * 4;
            var take = 4;
            var books = this.bookService.GetAll(searchString, skip, take);
            var totalBooks = this.bookService.GetCount();

            var totalPages = totalBooks / 4;
            if (totalBooks % 4 > 0)
            {
                totalPages++;
            }

            var model = new BookViewModel_List()
            {
                List = GetListofBooksViewModel(books),
                CurrentPage = currentPage,
                TotalPages = totalPages
            };
            return View(model);
        }

        // GET: Books/Details/5
        [AllowAnonymous]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = this.bookService.GetById(id);
            var model = GetBookViewModel(book);
            if (book == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // GET: Books/Create
       
        public IActionResult Create()
        {
            var book = new Book();
            book.AuthorList = (ICollection<SelectListItem>)this.bookService.CreateAuthorDropDownList();
            book.GenreList = (ICollection<SelectListItem>)this.bookService.CreateGenreDropDownList();
            var model = GetBookViewModel(book);
            return View(model);
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("BookId,Name,PictureUrl,Description,GenreId,AuthorId")] BookViewModel book)
        {
            if (ModelState.IsValid)
            {
                var bookToAdd = GetBookDataModel(book);
                if (BookExists(bookToAdd.Name))
                {
                    ModelState.AddModelError("name", "The book already exists");
                }
               
                else
                {
                    this.bookService.Add(bookToAdd);
                    this.bookService.AddBookInAuthor(bookToAdd);
                    this.bookService.AddBookInGenre(bookToAdd);
                    this.bookService.AddInAuthorGenre(bookToAdd);

                    return RedirectToAction(nameof(Index));
                }
            }
            
            return View(book);
        }
        public ActionResult AddAuthor(string authorName, string authorDescription, string pictureUrl)
        {
            var author = new Author();
            author.Name = authorName;
            author.Details = authorDescription;
            author.PictureUrl = pictureUrl;
            this.bookService.AddAuthor(author);
            var id = author.AuthorId;
            return Ok(new
            {
                Id = id,
                Name = authorName,
               
            }) ;
        }

        public IActionResult AddGenre(string genreName)
        {
            var genre = new Genre();
            genre.Name = genreName;
            this.bookService.AddGenre(genre);
            var id = genre.GenreId;
            return Ok(new
            {
                Id = id,
                Name = genreName,
            });
        }

        // GET: Books/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = this.bookService.GetById(id);
            book.AuthorList = (ICollection<SelectListItem>)this.bookService.CreateAuthorDropDownList();
            book.GenreList = (ICollection<SelectListItem>)this.bookService.CreateGenreDropDownList();
            var model = GetBookViewModel(book);

            if (book == null)
            {
                return NotFound();
            }
           
            return View(model);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("BookId,Name,PictureUrl, Description,GenreId,AuthorId")] BookViewModel book)
        {
            if (id != book.BookId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    this.bookService.Update(GetBookDataModel(book));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.BookId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
           
            return View(book);
        }

        // GET: Books/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = this.bookService.GetById(id);
            var model = GetBookViewModel(book);
            if (book == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var book = this.bookService.GetById(id);
            this.bookService.Delete(book);
            this.bookService.DeleteBookInAuthor(book);
            this.bookService.DeleteBookInGenre(book);
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return this.bookService.BookExists(id);
        }

        private bool BookExists(string bookName)
        {
            return this.bookService.BookExists(bookName);
        }

        private Book GetBookDataModel (BookViewModel book)
        {
            return new Book
            {
                BookId = book.BookId,
                Name = book.Name,
                PictureUrl = book.PictureUrl,
                Description = book.Description,
                AuthorId = book.AuthorId,
                Author = book.Author,
                GenreId = book.GenreId,
                Genre = book.Genre,
                AuthorList = book.AuthorList,
                GenreList = book.GenreList

            };
        }
        
        private BookViewModel GetBookViewModel(Book book)
        {
            var model = new BookViewModel()
            {
                BookId = book.BookId,
                Name = book.Name,
                PictureUrl = book.PictureUrl,
                Description = book.Description,
                AuthorId = book.AuthorId,
                Author = book.Author,
                GenreId = book.GenreId,
                Genre = book.Genre,
                AuthorList = book.AuthorList,
                GenreList = book.GenreList

            };
            return model;
        }

        private ICollection<BookViewModel> GetListofBooksViewModel(List<Book> sourse)
        {
            var books = new List<BookViewModel>();
            foreach (var g in sourse)
            {
                books.Add(GetBookViewModel(g));
            }
            return books;
        }
    }
}

FinalProject-2nd edition/Views/Genres/Create.cshtml
@model FinalProject_2nd_edition.Models.GenreViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Genre</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalProject-2nd edition/Views/Genres/Delete.cshtml
@model FinalProject_2nd_edition.Models.GenreViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>

<div>
    <h4>Genre</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name) <br />
            <span asp-validation-for="Name" class="text-danger"></span>
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="GenreId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalProject-2nd edition/Views/Genres/Details.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@model FinalProject_2nd_edition.Models.GenreViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>@Html.DisplayFor(model => model.Name)</h4>
    <hr />
    <dl class="row">
       
        <dt class="col-sm-2">

            @Html.DisplayNameFor(model => model.Books)
        </dt>
        <dd class="col-sm-10">
            <table class="table">
                @foreach (var item in Model.Books)
                {
                    <tr>
                        <td>
                           
                            <a asp-controller="Books" asp-action="Details" asp-route-id="@item.BookId">@Html.DisplayName(item.Name)</a>
                            
                        </td>

                    </tr>
                }
            </table>
        <dt class="col-sm-2">

            Authors
        </dt>
        <dd class="col-sm-10">
            <table class="table">
                    @foreach (var item in Model.Authors)
                    {
                    <tr>
                        <td>
                                
                                <a asp-controller="Authors" asp-action="Details" asp-route-id="@item.AuthorId">@Html.DisplayName(item.Name)</a>
                        </td>

                    </tr>
                    }
            </table>
        </dd>
    </dl>
</div>
<div>
    @if ((await AuthorizationService.AuthorizeAsync(User, "RequireAdministratorRole")).Succeeded)
    {
        <a asp-action="Edit" asp-route-id="@Model.GenreId">Edit</a>
    }
    <a asp-action="Index">Back to List</a>
</div>

FinalProject-2nd edition/Views/Genres/Edit.cshtml
@model FinalProject_2nd_edition.Models.GenreViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Genre</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GenreId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalProject-2nd edition/Views/Genres/Index.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@model FinalProject_2nd_edition.Models.GenreViewModel_List

@{
    ViewData["Title"] = "Index";
}

<h1>Genres</h1>
@if ((await AuthorizationService.AuthorizeAsync(User, "RequireAdministratorRole")).Succeeded)
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}
@using (Html.BeginForm())
{
    <p>
        Search by name: @Html.TextBox("SearchString")  
        <input type="submit" value="Search" /></p>
}
<table class="table">
    <thead>
        <tr>
            <th>
                Genre name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.List)
        {
            <tr>
                <td>
                   
                    <a asp-action="Details" asp-route-id="@item.GenreId">@item.Name</a>
                </td>
                <td>
                    
                    @if ((await AuthorizationService.AuthorizeAsync(User, "RequireAdministratorRole")).Succeeded)
                    {
                        <a asp-action="Edit" asp-route-id="@item.GenreId">Edit</a>
                        <a asp-action="Delete" asp-route-id = "@item.GenreId">Delete</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<nav aria-label="...">
        <ul class="pagination">
            @if (Model.CurrentPage == 1)
            {
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Previous</a>
                </li>
            }
            else
            {
                <li class="page-item">
                    <a class="page-link" href="/Genres/Index?currentPage=@(Model.CurrentPage-1)" tabindex="-1">Previous</a>
                </li>
            }
            @for (int i = 0; i < Model.TotalPages; i++)
            {
                if (i + 1 == Model.CurrentPage)
                {
                    <li class="page-item active">
                        <a class="page-link" href="/Genres/Index?currentPage=@(i + 1)">@(i + 1) <span class="sr-only">(current)</span></a>
                    </li>
                }
                else
                {
                    <li class="page-item"><a class="page-link" href="/Genres/Index?currentPage=@(i + 1)">@(i + 1)</a></li>
                }
            }

            @if (Model.CurrentPage == Model.TotalPages)
            {
                <li class="page-item disabled">
                    <a class="page-link" href="#">Next</a>
                </li>
            }
            else
            {
                <li class="page-item">
                    <a class="page-link" href="/Genres/Index?currentPage=@(Model.CurrentPage+1)">Next</a>
                </li>
            }

        </ul>
    </nav>